### ISSUE TITLE
directories disappear  after upgrade to FS version  version 1.2: deleted_inodes 

### ISSUE THREAD

**Issue by bhzhu203** [koverstreet/bcachefs-tools#157] opened 2023-08-12 11:54 UTC
all of the directories disappeared , only left one directory.  I have do the fsck two times using tools (f3976e3733e97a0e96f5fc6349d1e82b25116043) .

The  FS dump  link is sent to you via IRC.

I am doing the third  fsck , waiting too long here

```
  stripe_redundancy 0
  io_time[READ]     7735907848
  io_time[WRITE]    9699863048
  fragmentation     0
  bp_start          7
, fixing
 done
check_btree_backpointers... done
check_backpointers_to_extents... done
check_extents_to_backpointers... done
check_alloc_to_lru_refs... done
check_snapshot_trees... done
check_snapshots... done
check_subvols... done
```

**Comment by koverstreet** [comment] 2023-08-12 17:40
So, the filesystem you sent me has journal_transaction_names turned off, and you didn't save the fsck logs - so I won't be able to root cause this.

The most I'm going to be able to do is figure out why fsck isn't reattaching lost inodes/directories, since they're clearly still there.

**Comment by koverstreet** [comment] 2023-08-12 17:42
Also, if you're going to be communicating via IRC, _please_ don't do the link and run, it's rather rude - work with me a bit here.

**Comment by bhzhu203** [comment] 2023-08-14 01:04
[0814.txt](https://github.com/koverstreet/bcachefs-tools/files/12330843/0814.txt)

here is the  fsck  log

**Comment by bhzhu203** [comment] 2023-08-16 11:38
Hello is there any possible to recovery my FS？

**Comment by koverstreet** [comment] 2023-08-16 16:18
We're working on it

**Comment by koverstreet** [comment] 2023-08-28 20:36
This should be fixed now - is_ancestor had multiple bugs

**Closed by koverstreet** 2023-08-28 20:36 UTC
