### ISSUE TITLE
stuck in bch2_journal_read_device

### ISSUE THREAD

**Issue by FlyingWombat** [koverstreet/bcachefs-tools#116] opened 2022-04-08 18:00 UTC
I let `sudo bcachefs list_journal -a /dev/sdb /dev/sdd /dev/sde > bcachefs-list_journal.txt` run for about 6 hours and bloat to 4GB ram usage before killing it.

Built latest commit 7f77afa955e81da5a55b55e22e7e6f9fee1709a5 with debug enabled.

Program output only shows: `recovering from clean shutdown, journal seq 7866100`

perf top shows  
```
99.47%  bcachefs          [.] bch2_journal_read_device
```
Note that without debug enabled, perf top shows usage split between two symbols:
```
  46.36%  bcachefs          [.] 0x000000000004c9f3
  45.16%  bcachefs          [.] 0x000000000004c96c
   4.88%  bcachefs          [.] 0x000000000004c97f
   2.46%  bcachefs          [.] 0x000000000004c9e0
```

strace shows:
```
strace: Process 17001 attached
futex(0x5575513792bc, FUTEX_WAIT_PRIVATE, 2, NULL
```

Note: `bcachefs dump -j` works fine

Let me know what other info I can get for you.

**Comment by koverstreet** [comment] 2022-04-08 19:21
duplicate of https://github.com/koverstreet/bcachefs/issues/399

**Comment by koverstreet** [comment] 2022-04-08 23:30
Just fixed this

**Closed by koverstreet** 2022-04-08 23:30 UTC

**Comment by FlyingWombat** [comment] 2022-04-09 09:11
Still stuck.

Built commit 986533d8d5b21c8eb512bbb3f0496d3d2a087c5d with debug

Strace output is the same as before.
Perf top now shows the new __genradix_iter_peek function stuck in there too:

```
  69.23%  bcachefs          [.] bch2_journal_read_device
  30.07%  bcachefs          [.] __genradix_iter_peek
```
How can I help narrow down what is causing this?

**Comment by koverstreet** [comment] 2022-04-09 18:03
Try with the version I just pushed, it looks like it was in the loop to delete unneeded journal entries, which we don't want to be running when we're reading the entire journal.

**Comment by FlyingWombat** [comment] 2022-04-09 22:17
8b23ea867a45ead0e97c95a72c8fee40058c5b95 worked
Thanks!
